import psycopg2
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Database connection setup using environment variables
connection = psycopg2.connect(
    database=os.getenv('DB_NAME'),        # Database name from .env
    user=os.getenv('DB_USER'),            # Database username from .env
    password=os.getenv('DB_PASSWORD'),    # Database password from .env
    host=os.getenv('DB_HOST', 'localhost'), # Default to localhost if not set
    port=os.getenv('DB_PORT', '5432')     # Default to port 5432 if not set
)
cursor = connection.cursor()

# Corrected SQL statement generated by generate_sql_v1.py
create_table_sql = """
CREATE TABLE "all_stocks_ml" (
    "Order" INTEGER, "Symbol" TEXT, "Name" TEXT, "Current Price" FLOAT, 
    "Price % Chg" FLOAT, "% Chg YTD" FLOAT, "% Chg Cur Week" FLOAT, 
    "% Chg 1 Month" FLOAT, "Volume (1000s)" INTEGER, "Vol % Chg vs 10-Week" FLOAT, 
    "EPS Rating" INTEGER, "EPS Est Next Yr %" FLOAT, "Pre-tax Margins" FLOAT, 
    "Avg Sales % Chg 6Q" FLOAT, "Avg Sales % Chg 4Q" FLOAT, 
    "Sales % Chg Lst Qtr" INTEGER, "Market Cap (mil)" FLOAT, "ROE" FLOAT, 
    "Price to Sales" FLOAT, "% Off High" FLOAT, "Current Ratio" FLOAT, 
    "EV to FCF" FLOAT, "CF vs EPS % Last Qtr" FLOAT, "Debt %" INTEGER, "PEG" FLOAT, 
    "P/E" FLOAT, "Forward P/E" FLOAT, "Industry Name" TEXT, "Price to CF" FLOAT, 
    "Price to Book" FLOAT, "Ind Mkt Val (bil)" FLOAT, "ROE 5-Yr Avg" FLOAT, 
    "LT Debt to Working Cap" FLOAT, "Price $ Chg" FLOAT, "Liab to Assets Lss Ind Median" TEXT, 
    "CF vs EPS % Last Yr" FLOAT, "Weekly Closing Range" FLOAT, 
    "Prof Marg Geq Ind Median" TEXT, "Op Marg Geq Ind Median" TEXT, 
    "Vol % Chg vs 50-Day" FLOAT, "Avg AT Margin 2Q" FLOAT, "Avg AT Margin 4Q" FLOAT, 
    "Avg AT Margin 3Q" FLOAT, "AT Margin" FLOAT, "AT Margin Accel" TEXT, 
    "Short Volume" FLOAT, "Yield %" FLOAT, "Shrt Int % Chg" FLOAT, 
    "New CEO 12 Months" TEXT, "52-Wk Low" FLOAT, "52-Wk High" FLOAT, 
    "% New Lows in Group" FLOAT, "# New Lows in Group" INTEGER, 
    "Company Description" TEXT, "% New Highs in Group" FLOAT, 
    "# New Highs in Group" INTEGER, "Shrt Int % of Float" FLOAT, "ADR" TEXT, 
    "A/D Rating - Pr Wk" TEXT, "Incorp Date" FLOAT, "IPO Date" TEXT, 
    "Exchange" TEXT, "% Chg 12 Months" FLOAT, "% Chg 6 Months" FLOAT, 
    "% Chg 3 Months" FLOAT, "RS Rating" INTEGER, "Ind Group RS" TEXT, 
    "SMR Rating" TEXT, "Trl 26 Wk % Perf vs S&P 500" INTEGER, "Price vs 21-Day" FLOAT, 
    "Daily Closing Range" FLOAT, "Price vs 10-Day" FLOAT, "Price vs 50-Day" FLOAT, 
    "Price vs 150-Day" FLOAT, "Price vs 200-Day" FLOAT, 
    "10 Day > 21 Day > 50 Day" INTEGER, "50-Day > 150-Day > 200-Day" INTEGER, 
    "Current day's Volume greater than previous 5 days' Volume" INTEGER, 
    "50-Day Avg Vol (1000s)" FLOAT, "Current day's Volume greater than previous 10 days' Volume" INTEGER, 
    "Current day's Volume greater than previous 20 days' Volume" INTEGER, 
    "RS Line New High" TEXT, "Up/Down Vol" FLOAT, "50-Day Avg $ Vol (1000s)" INTEGER, 
    "RS Line New Low" TEXT, "RS Line Within 5% of New High" INTEGER, 
    "Alpha" FLOAT, "Sales % Chg Lst Yr" FLOAT, "Beta" FLOAT, "Avg True Range" FLOAT, 
    "Enterprise Val (mil)" FLOAT, "Number of Funds" INTEGER, "Funds % Increase" FLOAT, 
    "Funds %" INTEGER, "A/D Rating" TEXT, "Shares in Float (1000s)" INTEGER, 
    "Shares (1000s)" INTEGER, "Mgmt %" FLOAT, "Sales Growth 3 Yr" FLOAT, 
    "Sector" TEXT, "3-Yr EPS Growth Geq 5-Yr" TEXT, "EPS % Chg Last Qtr" FLOAT, 
    "Ind Group Rank" INTEGER, "Sales Accel 2 Qtrs" TEXT, "Annual Sales (mil)" FLOAT, 
    "Sales Accel 3 Qtrs" TEXT, "Avg Sales % Chg 2Q" FLOAT, "Comp Rating" FLOAT, 
    "EPS % Chg 1 Q Ago (-/+)" INTEGER, "EPS Est Cur Yr %" FLOAT, 
    "EPS Est Cur Qtr %" FLOAT, "EPS Surprise" FLOAT, "Sustainable Growth %" FLOAT, 
    "EPS Trailing 4 Qtrs" FLOAT, "Earnings Stability" FLOAT, "EPS Accel 3 Qtrs" TEXT, 
    "EPS Due Date" TEXT, "EPS Lst Rptd" TEXT, "Number of Stocks" INTEGER, 
    "Last Mark-up Date" FLOAT, "Days Vol Short 2 Periods Ago" FLOAT, 
    "Timeliness Rating - Pr Wk" TEXT, "Days Vol Short 1 Period Ago" FLOAT, 
    "Days Vol Short Current" FLOAT, "Pr Wk High($)" FLOAT, 
    "Ind Grp Rnk 6 Mo Ago" INTEGER, "Ind Grp Rnk 3 Mo Ago" INTEGER, 
    "Ind Grp Rnk Last Week" INTEGER, "Ex-Dividend Date" TEXT, 
    "Expected X Dividend Amount" FLOAT, "State" TEXT, "City" TEXT, 
    "Dividend-Adjusted PEG" FLOAT, "P/E Lss 5-Yr Avg" TEXT, 
    "P/E Ratio Rank in Grp" FLOAT, "P/E Percent Rank" FLOAT, 
    "P/E vs S&P 500 P/E (%)" FLOAT, "Avg AT Margin 6Q" FLOAT, 
    "Avg AT Margin 5Q" FLOAT, "EPS % Chg 1 Q Ago" FLOAT, "Timeliness Rating" TEXT, 
    "RS 6-Month Rating" INTEGER, "RS 3-Month Rating" INTEGER, 
    "Sponsor Rating" TEXT, "Sales Growth 5 Yr" FLOAT, 
    "Avg Sales % Chg 5Q" FLOAT, "Avg Sales % Chg 3Q" FLOAT, 
    "EPS % Chg 3 Q Ago (-/+)" INTEGER, "EPS % Chg 2 Q Ago (-/+)" INTEGER, 
    "EPS % Chg Last Qtr (-/+)" INTEGER, "EPS Lst Yr Gtr EPS 4 Yrs Ago" TEXT, 
    "Fiscal EPS 6 Yrs Ago" FLOAT, "Fiscal EPS 5 Yrs Ago" FLOAT, 
    "Fiscal EPS 4 Yrs Ago" FLOAT, "Fiscal EPS 2 Yrs Ago" FLOAT, 
    "Fiscal EPS 1 Yr Ago" FLOAT, "Fiscal EPS Lst Yr" FLOAT, 
    "EPS % Growth 5 Yr Pct Rnk" FLOAT, "EPS % Growth 5 Yr" FLOAT, 
    "EPS % Growth 3 Yr" FLOAT, "EPS % Growth 1 Yr" FLOAT, 
    "EPS % Chg 1 Yr Ago" INTEGER, "EPS % Chg Lst Yr" INTEGER, 
    "EPS Trl 4Q Geq EPS Lst Fiscal Yr" TEXT, "EPS Trl 4Q Gtr EPS 4 Yrs Ago" TEXT, 
    "Avg EPS % Chg 6Q" FLOAT, "Avg EPS % Chg 5Q" FLOAT, 
    "Avg EPS % Chg 4Q" FLOAT, "Avg EPS % Chg 3Q" FLOAT, 
    "Avg EPS % Chg 2Q" FLOAT, "EPS % Chg Lst Q Gtr 3-Yr Growth" TEXT, 
    "EPS % Chg 3 Q Ago" FLOAT, "EPS % Chg 2 Q Ago" FLOAT
);
"""

cursor.execute(create_table_sql)
connection.commit()

print("Table 'all_stocks_ml' created successfully.")

# Close the connection
cursor.close()
connection.close()
